name: Build project

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64  # Build a Windows 64-bit standalone.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          
      # - uses: actions/cache@v3
      #   with:
      #     path: EcoHome-VR/Library  # Cache the Library folder inside EcoHome-VR (Unity Project)
      #     key: Library-${{ matrix.targetPlatform }}
      #     restore-keys: Library-

      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1

      # Use game-ci/unity-builder to handle Unity installation and building
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: EcoHome-VR  # Path to the Unity project
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: '2021.3.14f1'
          buildsPath: '../EcoHome-Build'  # Build output outside the Unity project folder
          buildMethod: 'BuildScript.BuildGame'  # Specify the method to execute

      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: EcoHome-Build  # Path to the build output folder